stages:
  load_data:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/make_dataset.py
    - src/data/load_data.py
    - data_given/Real_combine.csv
    outs:
    - data/raw/Real_combine.csv

  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/raw/Real_combine.csv
    outs:
    - data/raw/train_data.csv
    - data/raw/test_data.csv

  feature_importance:
    cmd: python src/features/build_features.py --config=params.yaml
    deps:
      - src/features/build_features.py
      - data/raw/Real_combine.csv
    metrics:
      - reports/feature_importance.json

  train_and_evaluate:
    cmd: python src/models/train_model.py --config=params.yaml
    deps:
    - data/raw/train_data.csv
    - src/models/train_model.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.min_samples_split
    - estimators.RandomForestRegressor.params.min_samples_leaf
    - estimators.RandomForestRegressor.params.max_features
    - estimators.RandomForestRegressor.params.max_depth
    metrics:
    - reports/params.json:
        cache: false
    outs:
    - models/model.joblib

  evaluate_and_predict:
    cmd: python src/models/predict_model.py --config=params.yaml
    deps:
    - data/raw/test_data.csv
    - src/models/predict_model.py
    metrics:
    - reports/scores.json:
        cache: false

  visualization:
    cmd: python src/visualization/visualize.py --config=params.yaml
    deps:
      - data/raw/Real_combine.csv
      - data/raw/test_data.csv
      - src/models/predict_model.py
      - reports/feature_importance.json
    outs:
      - reports/figures/correlation_plot.png
      - reports/figures/feature_importance_plot.png
      - reports/figures/predict_scatter_plot.png
#  log_production_model:
#    cmd: python src/log_production_model.py --config=params.yaml
#    deps:
#    - src/log_production_model.py