stages:
  load_data:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/make_dataset.py
    - src/data/load_data.py
    - data_given/Real_combine.csv
    outs:
    - data/raw/Real_combine.csv

  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/raw/Real_combine.csv
    outs:
    - data/raw/train_data.csv
    - data/raw/test_data.csv

  feature_importance:
    cmd: python src/features/build_features.py --config=params.yaml
    deps:
      - src/features/build_features.py
      - data/raw/Real_combine.csv
    metrics:
      - reports/feature_importance.json

#
#  train_and_evaluate:
#    cmd: python src/train_and_evaluate.py --config=params.yaml
#    deps:
#    - data/processed/train_winequality.csv
#    - data/processed/test_winequality.csv
#    - src/train_and_evaluate.py
#    params:
#    - estimators.ElasticNet.params.alpha
#    - estimators.ElasticNet.params.l1_ratio
##    metrics:
##    - report/scores.json:
##        cache: false
##    - report/params.json:
##        cache: false
##    outs:
##    - saved_models/model.joblib
#  log_production_model:
#    cmd: python src/log_production_model.py --config=params.yaml
#    deps:
#    - src/log_production_model.py